### ISSUE TITLE
Difference viewing experience when running the demo localhost compare to the preview link 

### ISSUE THREAD

**Issue by wilsonwong13** [watson-developer-cloud/discovery-components#156]
When I run the demo locally, I see this
![Screen Shot 2020-08-18 at 11 37 26 AM](https://user-images.githubusercontent.com/23243527/90533976-310bb580-e147-11ea-93d6-2015997729fd.png)

I thought I would be seeing this

![Example app](https://raw.githubusercontent.com/watson-developer-cloud/discovery-components/master/docs/images/example-app.png)

**Comment by noah-eigenfeld** [comment]
@wilsonwong13 could you provide which OS you observed this problem on? Also, are you seeing any errors in the console?

I pulled down the latest code and ran the demo app locally (I'm on macOS), and got something that looks like this:
<img width="1437" alt="Screen Shot 2020-10-21 at 2 04 20 PM" src="https://user-images.githubusercontent.com/11284492/96766936-d4788100-13a9-11eb-98cf-671db213fccb.png">

While this is slightly different from the example screenshot in our documentation (which we should maybe update anyway), it still has most of the styling that seems to be missing in @wilsonwong13's screenshot. It looks to me like something might have gone wrong with the styling package (`packages/discovery-styles`) either during the build of the components (`packages/discovery-react-components`) or while starting the example app.

**Comment by wilsonwong13** [comment]
Hey Noah, I was referring to the code example in Discovery Components in a React application section
```
 // src/App.js
  import React from 'react';
  import {
    DiscoverySearch,
    SearchInput,
    SearchResults,
    SearchFacets,
    ResultsPagination,
    DocumentPreview
  } from '@ibm-watson/discovery-react-components';
  import DiscoveryV2 from 'ibm-watson/discovery/v2';
  import { BearerTokenAuthenticator } from 'ibm-watson/auth';
  import '@ibm-watson/discovery-styles/scss/index.scss';
  // Replace these values
  const bearerToken = '{REPLACE_ME}'; // retrieved from CP4D Admin UI under instance details which expires daily
  const url = '{REPLACE_ME}'; // retrieved from CP4D Admin UI under instance details
  const version = '{REPLACE_ME}'; // YYYY-MM-DD date format
  const projectId = '{REPLACE_ME}'; // retrieved from Discovery Tooling UI
  const App = () => {
    let authenticator, searchClient, success;
    try {
      // see https://github.com/IBM/node-sdk-core/blob/master/AUTHENTICATION.md#bearer-token-authentication
      authenticator = new BearerTokenAuthenticator({ bearerToken });
      searchClient = new DiscoveryV2({ url, version, authenticator });
      success = true;
    } catch (err) {
      console.error(err);
    }
    return success ? (
        <DiscoverySearch searchClient={searchClient} projectId={projectId}>
          <SearchInput />
          <SearchResults />
          <SearchFacets />
          <ResultsPagination />
          <DocumentPreview />
        </DiscoverySearch>
    ) : (
      setupMessage()
    );
  };
  function setupMessage() {
    return (
      <div style={{
        textAlign: 'center',
        margin: '20%',
        fontSize: '1.5rem',
      }}>
        Please replace the constants in App.js in order to see the Discovery sample application.
        <br /><br />
        Check the console log for more information if you have replaced these constants and are still seeing this message.
      </div>
    );
  }
  export default App;
```

**Comment by maniax89** [comment]
@wilsonwong13 so all the layout styling is found in https://github.com/watson-developer-cloud/discovery-components/blob/master/examples/discovery-search-app/src/app.scss at the time of this writing. there is also a bunch of layout-related divs that correspond to those styles in https://github.com/watson-developer-cloud/discovery-components/blob/master/examples/discovery-search-app/src/App.js

so unfortunately the base code example doesn't include layouts and styling as that is up to you on how you want to layout everything. the discovery-search-app example code is there in case you don't want to do all the layout to start from something concrete

**Comment by jhpedemonte** [comment]
Closing. Please re-open if you are still having this issue.
