### ISSUE TITLE
Gateway Time Out Issue

### ISSUE THREAD

**Issue by sujaysom** [watson-developer-cloud/discovery-components#169]
#### What package(s) (including version) are you using?
After deploying the code locally I am getting the following
Gateway Time-out: Gateway Time-out
    at RequestWrapper.formatError (/Users/sujaysom/Training/Watson/WatsonDiscovery/DiscoveryApps/discovery-components/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:275:21)
    at /Users/sujaysom/Training/Watson/WatsonDiscovery/DiscoveryApps/discovery-components/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:260:45
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async addAuthorization (/Users/sujaysom/Training/Watson/WatsonDiscovery/DiscoveryApps/discovery-components/examples/discovery-search-app/src/setupProxy.js:41:25) {
  statusText: 'Gateway Time-out',
  status: 504,
  code: 504,
  body: '"<html>\\r\\n<head><title>504 Gateway Time-out</title></head>\\r\\n<body>\\r\\n<center><h1>504 Gateway Time-out</h1></center>\\r\\n<hr><center>openresty</center>\\r\\n</body>\\r\\n</html>\\r\\n"',
  headers: {
    server: 'openresty',
    date: 'Mon, 25 Jan 2021 15:34:46 GMT',
    'content-type': 'text/html',
    'content-length': '164',
    connection: 'close'
  }
}
Is it a configuration issue or something else.. ?

**Comment by maniax89** [comment]
this most likely seems like a configuration issue - could you attempt to run the same API calls via `curl` or similar to validate that your targeted discovery instance is working as expected before attempting to point the example app at that instance

**Comment by sujaysom** [comment]
REACT_APP_PROJECT_ID=https://zen-cpd-zen.xxxx-cp4d-2.sc.xxx.com/discovery/core/projects/56513b63-b0a6-4597-a73b-75266a8d2cf8/workspace
CLUSTER_USERNAME=xxxxx
CLUSTER_PASSWORD=xxxxx
CLUSTER_PORT=443
CLUSTER_HOST=zen-cpd-zen.xxxx-cp4d-2.sc.xxx.com

I am using the above config.. 

https://zen-cpd-zen.dish-cp4d-2.sc.ibm.com/discovery/core/projects/56513b63-b0a6-4597-a73b-75266a8d2cf8/workspace. --> This URL If try in browser its taking me to the Login page and using the cluster username and password I am able to reach the WDS Project (Sample one).. Only information I would like to provide is CP4D Instance is in different Network (Connections are thru VPN).. And my mac is in normal network of our organization

**Comment by maniax89** [comment]
`REACT_APP_PROJECT_ID` should be a GUID, not a URL -> please see https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-deploy for how to get the project id

**Comment by maniax89** [comment]
in your post, it should just be `56513b63-b0a6-4597-a73b-75266a8d2cf8`

**Comment by sujaysom** [comment]
I have changed it to project Id.. Now its not going up it seems
Nothing I am getting in Log, its not up I think.. I have to rebuild?

**Comment by sujaysom** [comment]
After a long wait it went back to same error of Gateway Time Out (504)

**Comment by maniax89** [comment]
anything with `REACT_APP_` prefix is a build-time variable -> https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by sujaysom** [comment]
After re-installing the component.. I am getting the following error.. 

I can make curl call using the "https://zen-cpd-zen.xxxx-cp4d-2.sc.xxx.com:443/discovery/core/instances/1586056462214/api" URL but using Bearer Token.. Is that is the missing link?

[HPM] Error occurred while trying to proxy request //v2/projects/56513b63-b0a6-4597-a73b-75266a8d2cf8/query?version=2019-01-01 from 192.168.2.82:3000 to https://zen-cpd-zen.xxxx-cp4d-2.sc.xxx.com:443/discovery/core/instances/1586056462214/api (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
Error: socket hang up
    at connResetException (node:internal/errors:642:14)
    at TLSSocket.socketCloseListener (node:_http_client:467:25)
    at TLSSocket.emit (node:events:391:22)
    at node:net:667:12
    at TCP.done (node:_tls_wrap:573:7) {
  code: 'ECONNRESET'
}

**Comment by jhpedemonte** [comment]
We haven't seen an issue like this. If you are still having these problems, please re-open issue and add more details.
