### ISSUE TITLE
runExampleApp.sh need to enclose >> commands for environment files in quotes to avoid errors

### ISSUE THREAD

**Issue by maclean-stu** [watson-developer-cloud/discovery-components#187]
The code in runExampleApp.sh that creates the credentials file 

cat >$CREDENTIALS_FILE <<EOL

fails if the users path has spaces in directory names. Changing it to teh same surrounded by quotes 

cat >"$CREDENTIALS_FILE" <<EOL

corrects the problem.

The following lines are effected: 108, 127, 144, 149

**Comment by jhpedemonte** [comment]
Created PR https://github.com/watson-developer-cloud/discovery-components/pull/214
