### ISSUE TITLE
Step 3 of the Manual Setup is failing with errors

### ISSUE THREAD

**Issue by ajaybehuria** [watson-developer-cloud/discovery-components#190]
Microsoft Windows [Version 10.0.17134.2145]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\ABehuria>cd discovery-components && yarn
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @cypress/webpack-preprocessor@5.5.0" has unmet peer dependency "@babel/preset-env@^7.0.0".
warning "@storybook/addon-docs > vue-docgen-api > @vue/compiler-sfc@3.0.4" has incorrect peer dependency "vue@3.0.4".
[4/4] Building fresh packages...
[-/10] ⠄ waiting...
[-/10] ⠄ waiting...
[9/10] ⠄ node-sass
[-/10] ⡀ waiting...
error C:\Users\ABehuria\discovery-components\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\ABehuria\discovery-components\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\ABehuria\discovery-components\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\ABehuria\\discovery-components\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.7.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\ABehuria\discovery-components\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\ABehuria\discovery-components\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\ABehuria\discovery-components\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\ABehuria\discovery-components\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\ABehuria\discovery-components\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\ABehuria\discovery-components\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\ABehuria\discovery-components\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\ABehuria\discovery-components\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\ABehuria\discovery-components\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\ABehuria\discovery-components\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\ABehuria\discovery-components\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\ABehuria\discovery-components\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\ABehuria\AppData\Local\Programs\Python\Python37\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\ABehuria\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:12)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at maybeClose (node:internal/child_process:1069:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:300:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ABehuria\\discovery-components\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\ABehuria\discovery-components\node_modules\node-sass
gyp ERR! node -v v15.7.0

C:\Users\ABehuria\discovery-components>

**Comment by jhpedemonte** [comment]
I don't have access to a windows machine to reproduce this error. But it seems that when trying to install one of our dependencies (`node-sass`) it requires `python2`. It seems to have found a `python` executable, but perhaps it's a different version?

**Comment by jhpedemonte** [comment]
Closing. If this is still happening, please reopen.
