### ISSUE TITLE
Multiple module not found errors in clean create-react-app build sample

### ISSUE THREAD

**Issue by maclean-stu** [watson-developer-cloud/discovery-components#292]
I get multiple module not found error when following the guidance from the README.MD for Using Discovery Components in a React Application https://github.com/watson-developer-cloud/discovery-components#using-discovery-components-in-a-react-application

Steps to recreate (as per documented instructions.
1.  npx create-react-app myapp
2. cd myapp
3. npm install --save @ibm-watson/discovery-react-components @ibm-watson/discovery-styles ibm-watson carbon-components carbon-components-react carbon-icons
4. npm install --save-dev node-sass
5. Update src/App.js with sample code supplied
6. Update src/App.js to replace version and projectID placeholders
7. Download an ibm-credentials.env file
8. npm start

The following errors are reported:
Compiled with problems:X

ERROR in ./node_modules/buffer-equal-constant-time/index.js 4:13-37

Module not found: Error: Can't resolve 'buffer' in '/Users/sjm/Downloads/app-ds/node_modules/buffer-equal-constant-time'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }

ERROR in ./node_modules/ibm-cloud-sdk-core/auth/utils/file-reading-helpers.js 30:11-24

Module not found: Error: Can't resolve 'fs' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/auth/utils'

ERROR in ./node_modules/ibm-cloud-sdk-core/auth/utils/file-reading-helpers.js 32:11-24

Module not found: Error: Can't resolve 'os' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/auth/utils'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

ERROR in ./node_modules/ibm-cloud-sdk-core/auth/utils/file-reading-helpers.js 34:13-28

Module not found: Error: Can't resolve 'path' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/auth/utils'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/ibm-cloud-sdk-core/lib/content-type.js 23:13-28

Module not found: Error: Can't resolve 'path' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/ibm-cloud-sdk-core/lib/helper.js 42:13-28

Module not found: Error: Can't resolve 'path' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js 202:14-30

Module not found: Error: Can't resolve 'https' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
	- install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "https": false }

ERROR in ./node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js 206:20-42

Module not found: Error: Can't resolve 'querystring' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/lib'
Did you mean './querystring'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules, /Users/sjm/Downloads/app-ds/node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
	- install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "querystring": false }

ERROR in ./node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js 208:13-28

Module not found: Error: Can't resolve 'zlib' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
	- install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "zlib": false }

ERROR in ./node_modules/ibm-cloud-sdk-core/node_modules/dotenv/lib/main.js 24:11-24

Module not found: Error: Can't resolve 'fs' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/node_modules/dotenv/lib'

ERROR in ./node_modules/ibm-cloud-sdk-core/node_modules/dotenv/lib/main.js 26:13-28

Module not found: Error: Can't resolve 'path' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-cloud-sdk-core/node_modules/dotenv/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/ibm-watson/lib/common.js 8:9-22

Module not found: Error: Can't resolve 'os' in '/Users/sjm/Downloads/app-ds/node_modules/ibm-watson/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

ERROR in ./node_modules/isstream/isstream.js 1:13-30

Module not found: Error: Can't resolve 'stream' in '/Users/sjm/Downloads/app-ds/node_modules/isstream'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }

ERROR in ./node_modules/jwa/index.js 5:13-30

Module not found: Error: Can't resolve 'crypto' in '/Users/sjm/Downloads/app-ds/node_modules/jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

ERROR in ./node_modules/jwa/index.js 9:11-26

Module not found: Error: Can't resolve 'util' in '/Users/sjm/Downloads/app-ds/node_modules/jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

ERROR in ./node_modules/jws/lib/data-stream.js 4:13-30

Module not found: Error: Can't resolve 'stream' in '/Users/sjm/Downloads/app-ds/node_modules/jws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }

ERROR in ./node_modules/jws/lib/data-stream.js 6:11-26

Module not found: Error: Can't resolve 'util' in '/Users/sjm/Downloads/app-ds/node_modules/jws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

ERROR in ./node_modules/jws/lib/sign-stream.js 8:13-30

Module not found: Error: Can't resolve 'stream' in '/Users/sjm/Downloads/app-ds/node_modules/jws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }

ERROR in ./node_modules/jws/lib/sign-stream.js 12:11-26

Module not found: Error: Can't resolve 'util' in '/Users/sjm/Downloads/app-ds/node_modules/jws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

ERROR in ./node_modules/jws/lib/tostring.js 2:13-37

Module not found: Error: Can't resolve 'buffer' in '/Users/sjm/Downloads/app-ds/node_modules/jws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }

ERROR in ./node_modules/jws/lib/verify-stream.js 8:13-30

Module not found: Error: Can't resolve 'stream' in '/Users/sjm/Downloads/app-ds/node_modules/jws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }

ERROR in ./node_modules/jws/lib/verify-stream.js 12:11-26

Module not found: Error: Can't resolve 'util' in '/Users/sjm/Downloads/app-ds/node_modules/jws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

ERROR in ./node_modules/mime-types/index.js 15:14-37

Module not found: Error: Can't resolve 'path' in '/Users/sjm/Downloads/app-ds/node_modules/mime-types'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/safe-buffer/index.js 2:13-30

Module not found: Error: Can't resolve 'buffer' in '/Users/sjm/Downloads/app-ds/node_modules/safe-buffer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }

ERROR in ../node_modules/@ibm-watson/discovery-styles/scss/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!../node_modules/@ibm-watson/discovery-styles/scss/index.scss)

Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Cannot find module 'sass'
Require stack:
- /Users/sjm/Downloads/app-ds/node_modules/sass-loader/dist/utils.js
- /Users/sjm/Downloads/app-ds/node_modules/sass-loader/dist/index.js
- /Users/sjm/Downloads/app-ds/node_modules/sass-loader/dist/cjs.js
- /Users/sjm/Downloads/app-ds/node_modules/loader-runner/lib/loadLoader.js
- /Users/sjm/Downloads/app-ds/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/sjm/Downloads/app-ds/node_modules/webpack/lib/NormalModule.js
- /Users/sjm/Downloads/app-ds/node_modules/webpack-manifest-plugin/dist/index.js
- /Users/sjm/Downloads/app-ds/node_modules/react-scripts/config/webpack.config.js
- /Users/sjm/Downloads/app-ds/node_modules/react-scripts/scripts/start.js

ERROR in ../node_modules/@ibm-watson/discovery-styles/scss/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!../node_modules/@ibm-watson/discovery-styles/scss/index.scss)

Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  PostCSS received undefined instead of CSS string
  at new Input (/Users/sjm/Downloads/app-ds/node_modules/resolve-url-loader/node_modules/postcss/lib/input.js:38:13)
    at encodeError (/Users/sjm/Downloads/app-ds/node_modules/resolve-url-loader/index.js:287:12)
    at onFailure (/Users/sjm/Downloads/app-ds/node_modules/resolve-url-loader/index.js:228:14)

**Comment by jhpedemonte** [comment]
Odd, I thought I got this working recently. Will test again.

**Comment by jhpedemonte** [comment]
This is due to the use of Webpack 5 in `create-react-app` (CRA) v5. Ordinarily, since we're using `ibm-watson`, we would configure `webpack` to ignore the Node.js-specific dependencies, as specified in the `ibm-watson` [docs](https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack#webpack-configuration).

However, CRA doesn't allow for that. There is an [open issue](https://github.com/facebook/create-react-app/issues/11756) for v5 about these Node.js polyfills. There appears to be [some work](https://github.com/facebook/create-react-app/pull/11764) being done to add these back into the 5.x line, so perhaps this will be fixed in the near future.

For now, there are a couple of options available:
1. Downgrade to `create-react-app` v4.0.3.
2. Use CRA 5 and eject, so that you have access to the `webpack.config.js` file, where you can add the configuration specified by `ibm-watson`.
3. Use CRA 5 and install [craco](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#installation) (or similar pkg) to allow updating the `webpack` config without ejecting.

**Comment by jhpedemonte** [comment]
If you want to use `craco` with CRA v5, this seems to work:

```sh
yarn add -D @craco/craco@7.0.0-alpha.0
yarn add assert browserify-zlib buffer crypto-browserify https-browserify os-browserify path-browserify process querystring-es3 stream-browserify stream-http url util
```

Then create a file named `craco.config.js` (at the top level of the project) with these contents:

```js
// craco.config.js
const webpack = require("webpack");

module.exports = {
  webpack: {
    configure: {
      // @see https://webpack.js.org/configuration/resolve/#resolvefallback
      // @see https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack#webpack-configuration
      resolve: {
        fallback: {
          assert: require.resolve('assert'),
          buffer: require.resolve('buffer'),
          crypto: require.resolve('crypto-browserify'),
          fs: false,
          http: require.resolve('stream-http'),
          https: require.resolve('https-browserify'),
          module: false,
          net: false,
          os: require.resolve('os-browserify/browser'),
          path: require.resolve('path-browserify'),
          process: require.resolve('process/browser'),
          querystring: require.resolve('querystring-es3'),
          stream: require.resolve('stream-browserify'),
          tls: false,
          url: require.resolve('url'),
          util: require.resolve('util'),
          zlib: require.resolve('browserify-zlib')
        }
      },
      plugins: [
        new webpack.ProvidePlugin({
          process: "process/browser.js"
        })
      ]
    }
  }
};
```

That'll get it working with CRA v5.

However, the credentials instructions are wrong. I'm working on updating those as well.

**Comment by maclean-stu** [comment]
Thanks for the quick response. Hoping CRA will provide an update so we can avoid all the work arounds.

**Comment by jhpedemonte** [comment]
I created a PR to update our README with more information on how to properly handle authentication and notes on webpack/CRA v5: https://github.com/watson-developer-cloud/discovery-components/pull/297.
