### ISSUE TITLE
PDF viewer is broken when changing `page` props

### ISSUE THREAD

**Issue by wataken-ibm** [watson-developer-cloud/discovery-components#314]
#### Description

> Please describe the issue you are having.
> Include what you expected to happen and what happened instead.

When change page props for `PdfViewerWithHighlight`, the PDF view will be broken.

> In which browser(s) did you see the issue?

Happened with Chrome and FireFox.

#### What package(s) (including version) are you using?

`"@ibm-watson/discovery-react-components": "1.5.0-beta.23"`

#### Steps to reproduce the issue

1. Rendering document with `PdfViewerWithHighlight` without file data
2. Change `page` prop
3. PDF view will be broken.

Test document: [doc.json.zip](https://github.com/watson-developer-cloud/discovery-components/files/8159064/doc.json.zip)

#### Additional information

* Please add screenshots or other visual aids to represent the issue as applicable.

![pagination-bug3](https://user-images.githubusercontent.com/73686464/156113214-ea76c92e-6607-4df6-b04b-c990f31d9545.gif)

**Comment by fukudasjp** [comment]
It looks like the `transformation` set to `canvas` remains after PDF page rendering when PDF page rendering is interrupted. The transformation is used in page rendering next time. So, the page is rendered wrongly.
