### ISSUE TITLE
PDF highlighting only works if whole document is labeled as text

### ISSUE THREAD

**Issue by thomasirmer** [watson-developer-cloud/discovery-components#321]
#### Description

When passing a `highlight` to the document preview you can provide `start_offset`, `end_offset`, and `field`. If `field`'s value is not `text` then it is represented as an array with all the document's sentences as entries and not a single string or an array with length == 1. The highlighting however only accepts a `start_offset` and `end_offset` within the length of the first array index.

```js
// index.es.js @ line 114698
// NOTE that the fieldIndex is hardcoded to 0

function convertToDocumentFieldHighlights(passage, _a) {
    var _b = _a === void 0 ? {} : _a, _c = _b.id, id = _c === void 0 ? DEFAULT_HIGHLIGHT_ID : _c, className = _b.className;
    return [
        {
            id: id,
            className: className,
            field: passage.field || '',
            fieldIndex: 0,
            location: {
                begin: passage.start_offset || 0,
                end: passage.end_offset || 0
            }
        }
    ];
}
```

Our suggestion is to allow the passing of a fieldIndex as

```js
return [
        {
            id: id,
            className: className,
            field: passage.field || '',
            fieldIndex: passage.fieldIndex || 0,
            location: {
                begin: passage.start_offset || 0,
                end: passage.end_offset || 0
            }
        }
    ];
```

The underlying problem however is that the Watson Discovery API will only give you the location (`begin` and `end`) of a detected entity within it's sentence. See the following example:

```json
{
  "document_type": "documentation",
  "paragraph_name": "header-section",
  "coordinates": {
    "end": 115,
    "begin": 100
  },
  "document_id": "f3ed8e3a...",
  "value_at_position": "WatsonDiscovery"
}
```

If the entity "WatsonDiscovery" was found in the 5th sentence however, you cannot highlight it. You would have to pass `fieldIndex: 4` in order to make it work. In our case we calculate this fieldIndex by a string search through all array elements. If the string "WatsonDiscovery" can be found at `sentence[begin:end]` we assume it to be in that sentence.

#### What package(s) (including version) are you using?

@ibm-watson/discovery-react-components @ 1.5.0-beta.27

**Comment by jhpedemonte** [comment]
Thanks for the detailed report. We'll take a look soon.

**Comment by jhpedemonte** [comment]
Fixed by https://github.com/watson-developer-cloud/discovery-components/pull/430.

Note that the `highlight` property of `DocumentPreview` treats the referenced field as a single string. If the field value is an array of strings, then the string values are concatenated, separated by a `\n`. The offsets, then, are based on this generated string.
